version: "3"
services:
  frontend:
    image: ghcr.io/buka-lnc/opendoc-frontend:latest
    ports:
      - "3000:3000"
    environment:
      NUXT_API_BASE_ORIGIN: http://backend:8080
  backend:
    image: ghcr.io/buka-lnc/opendoc-backend:latest
    ports:
      - "8080:8080"
    environment:
      MIGRATION: true
      MYSQL__HOST: mysql
      MYSQL__PORT: 3306
      MYSQL__USER: opendoc
      MYSQL__PASSWORD: opendoc
      MYSQL__DB_NAME: opendoc
      REGISTER__URL: http://127.0.0.1:4873
    depends_on:
      mysql:
        condition: service_healthy
  compiler:
    image: ghcr.io/buka-lnc/opendoc-compiler:latest
    ports:
      - "9000:9000"
  mysql:
    image: mysql:8
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: opendoc
      MYSQL_USER: opendoc
      MYSQL_PASSWORD: opendoc
  verdaccio:
    image: verdaccio/verdaccio
    ports:
      - "4873:4873"
    configs:
      - source: verdaccio_conf.yaml
        target: /verdaccio/conf/config.yaml
configs:
  verdaccio_conf.yaml:
    content: |
      storage: /verdaccio/storage/data
      plugins: /verdaccio/plugins
      web:
        title: Opendoc Compiler Test
      uplinks:
        npmjs:
          url: https://registry.npmjs.org/
      packages:
        '@*/*':
          # scoped packages
          access: $$all
          publish: $$all
          unpublish: $$all
          proxy: npmjs
        '**':
          access: $$all
          publish: $$all
          unpublish: $$all
          proxy: npmjs
      server:
        keepAliveTimeout: 60
      publish:
        allow_offline: true
      middlewares:
        audit:
          enabled: true
