version: "3"
services:
  frontend:
    image: ghcr.io/buka-lnc/opendoc-frontend:latest
    ports:
      - "3000:3000"
    environment:
      NUXT_API_BASE_ORIGIN: http://backend:8080
  backend:
    image: ghcr.io/buka-lnc/opendoc-backend:latest
    ports:
      - "8080:8080"
    environment:
      MIGRATION: true
      MYSQL__HOST: mysql
      MYSQL__PORT: 3306
      MYSQL__USER: opendoc
      MYSQL__PASSWORD: opendoc
      MYSQL__DB_NAME: opendoc
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:8
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: opendoc
      MYSQL_USER: opendoc
      MYSQL_PASSWORD: opendoc
