name: Auto Assign
on:
  pull_request:
    types: [opened]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-assign@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          addReviewers: false
          addAssignees: true
          assignees: val-istar-guo
          skipDraft: true
